Microverse: Module1 Capstone
kessie2862/microverse-capstone-1 pull request #1
Opened 2023-04-20 14:03 UTC by kessie2862

In this branch, I

- [ ] Included various linter config files
- [ ] Added two HTML pages, **i.e** index.html and about.html
- [ ] Styled the two HTML pages and used media query to make them responsive
- [ ] Added all the project images
- [ ] Included a javascript file containing the functionality for the mobile nav menu and dynamically created the speaker's section.
- [ ] Added the project's live link to the README and a loom video recording describing the project.

2023-04-20 19:30 UTC, AbayomiOlaoye requested changes
## STATUS: CHANGE REQUIRED ♻️ 

Hi @kessie2862 :wave: , 

Good job with this milestone so far! What a brilliant attempt!!
There are just a few more issues to work on before moving on to the next project but you are almost there!

![so_close](https://camo.githubusercontent.com/0c690ab997907a8c79afe7e695c891f6398cdbef93eaf8ce19f652ff321b54f8/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f744b797263304e546c4563475764546870342f67697068792e676966)

## Highlights
- Descriptive Pull Request message :heavy_check_mark: 
- Good use of GitHub flow :heavy_check_mark: 
- Meaningful commit messages :heavy_check_mark: 
- No linter error :heavy_check_mark: 
- Great capstone attempt :heavy_check_mark: 
- Video presentation is impressively documentary :heavy_check_mark: 
- Descriptive ReadMe documentation :heavy_check_mark: 
- Smoothly responsive webpages :heavy_check_mark: 

## Required Changes ♻️
- [ ] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-20 19:30 UTC, AbayomiOlaoye commented on about.html
> +      </section>
- Great job with your implementation here, @kessie2862 :clap: but I believe there are a few touches you can still give this to improve its user interface, as well as improve user experience. Check this comparison out:

|Your Design| Figma Design|
|:--------------:|:-----------------:|
|![image](https://user-images.githubusercontent.com/99715640/233461215-c24bfc8e-80e1-4272-a6fd-1afb159bedd8.png)|![image](https://user-images.githubusercontent.com/99715640/233461528-4b19dd0d-f4b6-41c5-9719-633126ce45ed.png)|

- Kindly notice the following:
- [ ] [OPTIONAL] The `h1` seems to have a different `font-family`and `font-size` from the requirement
- [ ] Also, it appears the `h1` is not at the center of the columnar section unlike what we have in Cindy's design
- [ ] To also match the design as good as possible, I suggest that you implement that divider between the `title` and the paragraph.

2023-04-20 19:30 UTC, AbayomiOlaoye commented on about.html
> +        </p>
- [ ] I believe you just merged two sections into one which might not necessarily be the best approach here. How about breaking this up, and then include the currently missing logo that you were introducing in your paragraph just as it is in the design? :hugs: 

_Check this out:_
|Your Design| Figma Design|
|:--------------:|:-----------------:|
|![image](https://user-images.githubusercontent.com/99715640/233463246-d23bcceb-71d4-4029-84c1-ab1df58166a0.png)|![image](https://user-images.githubusercontent.com/99715640/233463428-1e6bcc3c-d3a1-40af-9cba-e48474a16e20.png)|

- Looks like title here also has a divider

2023-04-20 19:30 UTC, AbayomiOlaoye commented on about.html
> +      </div>
- [ ] As I mentioned above, consider breaking this into another section. That will really make your code more cleanly organized :wink:

2023-04-20 19:30 UTC, AbayomiOlaoye commented on index.html
> +          </div>
- [ ] Good job, @kessie2862 :clap: However, I suppose these texts can be aligned centrally unlike the `left-alignment` like we have in the template to really make the design more appealing :wink: 

|Your Design| Figma Design|
|:--------------:|:-----------------:|
|![image](https://user-images.githubusercontent.com/99715640/233465394-6cf880e7-7447-404a-936d-e4c248a72b4f.png)|![image](https://user-images.githubusercontent.com/99715640/233465562-8b90d792-b825-4c51-872d-87491a6c297a.png)|

2023-04-20 19:30 UTC, AbayomiOlaoye commented on index.html
> +        </h1>
- Impressive :+1: :clap: :clap: 
- [ ] How about fully implementing appropriate font styles - styling and family, and size for this `h1` element this?

|Your Design| Figma Design|
|:--------------:|:-----------------:|
|![image](https://user-images.githubusercontent.com/99715640/233466810-4d9134d9-9171-4d6d-bc34-26f6846731b1.png)|![image](https://user-images.githubusercontent.com/99715640/233466894-af1b19f2-5022-4dbc-a51d-90a1f1b69f32.png)|

2023-04-20 19:38 UTC, kessie2862 commented on about.html
> +      </section>
I don't know if we were given any other font family apart from **LATO** cos that's the font family I used.

2023-04-20 19:53 UTC, AbayomiOlaoye commented on about.html
> +      </section>
Oh, wait a minute @kessie2862 I will get you `cocogoose` now. I am sure you will like the feel

2023-04-20 19:58 UTC, AbayomiOlaoye commented on about.html
> +      </section>
...And here is the link to import cocogoose for your use: 
```
@import url('http://fonts.cdnfonts.com/css/cocogoose');

2023-04-20 20:01 UTC, kessie2862 commented on about.html
> +      </section>
I will appreciate that.

2023-04-21 07:30 UTC, tufoinnkuo10 approved these changes
## Status: Approved :heavy_check_mark:✔️ ✔️✔️ ✔️

Hi @kessie2862  ✔️ ✔️

Your project is complete! Great job for implementing the changes requested by the previous reviewer🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍✔️ ✔️
- Descriptive Pull Request ✔️ ✔️
- Great design✔️ ✔️
- professional readme✔️ ✔️
- work well presented✔️ ✔️
- No linter errors✔️ ✔️

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

![tufoin](https://media.giphy.com/media/ZOZzPhtZBTLBzwgew5/giphy.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-21 07:37 UTC, merged